apiVersion: v1
kind: Pod
metadata:
  name: ccmp-reduce-1993
spec:
  volumes:
    - name: ccmp
      persistentVolumeClaim:
        claimName: ccmp
  containers:
  - name: ccmp
    imagePullPolicy: Always
    image: argovis/ccmp:reduce
    #command: ['sleep', '100000000']
    command: ['cargo', 'run', '1993']
    volumeMounts:
      - mountPath: "/tmp"
        name: ccmp
    resources:
      requests:
        memory: "0Gi"
        cpu: "0m"
      limits:
        memory: 5400Mi
        cpu: 1350m
  restartPolicy: Never
